version: '3.5'

services:
  app:
    image: vacation-trek-api:latest
    build: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - 3333:3333
  
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres

    volumes:
      - postgres-db:/data/postgres
    ports:
      - 5432:5432

volumes:
  app:
    driver: local
  postgres-db:
    driver: local